# Generated by Django 3.2.3 on 2021-07-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_auto_20210708_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCustomer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('balance', models.IntegerField()),
                ('branchname', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('scheme', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
