# Generated by Django 3.2.3 on 2021-07-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_auto_20210715_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
